### ISSUE TITLE
Reordering keys that weren't touched makes diffs noisy

### ISSUE THREAD

**Issue by jasonmobley** [Anifacted/lerna-update-wizard#51]
Just tried the tool out and the diff shows that the `version`, `engines`, `typings` etc top-level keys in package.json have all been reordered arbitrarily. They don't appear to be alphabetized.

On top of that, the keys within the `scripts` section were reordered ~~to no longer be alphabetized~~! Why!? Edit: looks like they are alphabetical except for `foo` and `postfoo` being made adjacent. Still, this is undesirable.

This creates a ton of diff noise that either has to be carefully reverted or painfully absorbed by other contributors.

**Comment by jasonmobley** [comment]
Looks like this is because of `prettier-package-json` formatting the output before writing the file. A flag to opt out of this behavior would be really nice.

**Comment by Anifacted** [comment]
Yes, I did worry that it might be a little invasive, but due to time constraints, I went with `prettier-package-json`. I suppose it wouldn't be too big of a refactor to switch to only ordering the `dependencies`/`devDependencies`/`peerDependencies` keys and leave the rest untouched. The goal is essentially to mimic what NPM does as closely as possible.

**Comment by Anifacted** [comment]
@jasonmobley As of `v0.17.2` we're no longer depending on `prettier-package-json`, instead only sorting the keys of `dependencies`, `devDependencies` and `peerDependencies`.

I hope this leaves your package.json files in a nicer state after the modifications :)

**Comment by jasonmobley** [comment]
Thanks @Anifacted !
