### ISSUE TITLE
Adding/updating peer dependency generates exact version

### ISSUE THREAD

**Issue by crutch12** [Anifacted/lerna-update-wizard#71]
I had peer dependency `"lodash": "^4.17.11"` in one package
And just dependency `"lodash": "^4.17.11"` in another two packages

I ran update command and got peer dependency `"lodash": "4.17.15"` (exact version, not ^)
Another two packages has `"lodash": "^4.17.15"` (with ^)

Why does it happen?

Because of this when I try to update lodash again, I see I have two lodash versions:
```
Starting update wizard for @org/front

? Select a dependency to upgrade: lodash (2 versions)

? Select packages to affect: @org/common (4.17.15), @org/proj1 (^4.17.15), @org/proj2 (^4.17.15)
? Select version to install:
...
```

How can I avoid this behaviour and install peer dependency with ^?

Thanks, lib is awesome

**Comment by Anifacted** [comment]
Hi @crutch12,
Sorry for the late reply. It's surprising to me that you end up with two different version prefixes. Did you explicitly specify the `^` via the left/right-arrow feature as described here: https://github.com/Anifacted/lerna-update-wizard/pull/29?

Otherwise, it seems that NPM is treating peer and normal dependencies differently in this case. Let me know.

**Comment by crutch12** [comment]
Aww... I didn't know about left/right-arrow, it solves my problem.
I haven't seen this TIP before :D

> Otherwise, it seems that NPM is treating peer and normal dependencies differently in this case. Let me know.

Looks like that. Without left/right-arrow feature **peerDependencies** and **dependencies** lodashes have different version prefixes (**exact** and **^**)
